CFLAGS=$(shell pkg-config --cflags gstreamer-1.0 glib-2.0 gobject-2.0)
LDLIBS=$(shell pkg-config --libs gstreamer-1.0 glib-2.0 gobject-2.0)

all: simple-recording tee-recording-and-display dynamic-recording
